<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class A_propo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('A_propo_model');
    } 

    /*
     * Listing of a_propos
     */
    function index()
    {
        $data['a_propos'] = $this->A_propo_model->get_all_a_propos();
        
        $data['_view'] = 'a_propo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new a_propo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'NOM' => $this->input->post('NOM'),
				'DESCRIPTION' => $this->input->post('DESCRIPTION'),
            );
            
            $a_propo_id = $this->A_propo_model->add_a_propo($params);
            redirect('a_propo/index');
        }
        else
        {            
            $data['_view'] = 'a_propo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a a_propo
     */
    function edit($ID)
    {   
        // check if the a_propo exists before trying to edit it
        $data['a_propo'] = $this->A_propo_model->get_a_propo($ID);
        
        if(isset($data['a_propo']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'NOM' => $this->input->post('NOM'),
					'DESCRIPTION' => $this->input->post('DESCRIPTION'),
                );

                $this->A_propo_model->update_a_propo($ID,$params);            
                redirect('a_propo/index');
            }
            else
            {
                $data['_view'] = 'a_propo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The a_propo you are trying to edit does not exist.');
    } 

    /*
     * Deleting a_propo
     */
    function remove($ID)
    {
        $a_propo = $this->A_propo_model->get_a_propo($ID);

        // check if the a_propo exists before trying to delete it
        if(isset($a_propo['ID']))
        {
            $this->A_propo_model->delete_a_propo($ID);
            redirect('a_propo/index');
        }
        else
            show_error('The a_propo you are trying to delete does not exist.');
    }
    
}
