<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Acce extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Acce_model');
    } 

    /*
     * Listing of acces
     */
    function index()
    {
        $data['acces'] = $this->Acce_model->get_all_acces();
        
        $data['_view'] = 'acce/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new acce
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'NOM' => $this->input->post('NOM'),
				'NIVEAU' => $this->input->post('NIVEAU'),
            );
            
            $acce_id = $this->Acce_model->add_acce($params);
            redirect('acce/index');
        }
        else
        {            
            $data['_view'] = 'acce/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a acce
     */
    function edit($ID)
    {   
        // check if the acce exists before trying to edit it
        $data['acce'] = $this->Acce_model->get_acce($ID);
        
        if(isset($data['acce']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'NOM' => $this->input->post('NOM'),
					'NIVEAU' => $this->input->post('NIVEAU'),
                );

                $this->Acce_model->update_acce($ID,$params);            
                redirect('acce/index');
            }
            else
            {
                $data['_view'] = 'acce/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The acce you are trying to edit does not exist.');
    } 

    /*
     * Deleting acce
     */
    function remove($ID)
    {
        $acce = $this->Acce_model->get_acce($ID);

        // check if the acce exists before trying to delete it
        if(isset($acce['ID']))
        {
            $this->Acce_model->delete_acce($ID);
            redirect('acce/index');
        }
        else
            show_error('The acce you are trying to delete does not exist.');
    }
    
}
