<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contact_info extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Contact_info_model');
    } 

    /*
     * Listing of contact_info
     */
    function index()
    {
        $data['contact_info'] = $this->Contact_info_model->get_all_contact_info();
        
        $data['_view'] = 'contact_info/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new contact_info
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'STATUT' => $this->input->post('STATUT'),
				'NOM' => $this->input->post('NOM'),
				'TEXTE' => $this->input->post('TEXTE'),
				'CLASS' => $this->input->post('CLASS'),
            );
            
            $contact_info_id = $this->Contact_info_model->add_contact_info($params);
            redirect('contact_info/index');
        }
        else
        {            
            $data['_view'] = 'contact_info/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a contact_info
     */
    function edit($ID)
    {   
        // check if the contact_info exists before trying to edit it
        $data['contact_info'] = $this->Contact_info_model->get_contact_info($ID);
        
        if(isset($data['contact_info']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'STATUT' => $this->input->post('STATUT'),
					'NOM' => $this->input->post('NOM'),
					'TEXTE' => $this->input->post('TEXTE'),
					'CLASS' => $this->input->post('CLASS'),
                );

                $this->Contact_info_model->update_contact_info($ID,$params);            
                redirect('contact_info/index');
            }
            else
            {
                $data['_view'] = 'contact_info/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The contact_info you are trying to edit does not exist.');
    } 

    /*
     * Deleting contact_info
     */
    function remove($ID)
    {
        $contact_info = $this->Contact_info_model->get_contact_info($ID);

        // check if the contact_info exists before trying to delete it
        if(isset($contact_info['ID']))
        {
            $this->Contact_info_model->delete_contact_info($ID);
            redirect('contact_info/index');
        }
        else
            show_error('The contact_info you are trying to delete does not exist.');
    }
    
}
