<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Exercice extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Exercice_model');
    } 

    /*
     * Listing of exercice
     */
    function index()
    {
        $data['exercice'] = $this->Exercice_model->get_all_exercice();
        
        $data['_view'] = 'exercice/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new exercice
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'STATUT' => $this->input->post('STATUT'),
				'IDIMAGE' => $this->input->post('IDIMAGE'),
				'NOM' => $this->input->post('NOM'),
				'DESCRIPTION' => $this->input->post('DESCRIPTION'),
            );
            
            $exercice_id = $this->Exercice_model->add_exercice($params);
            redirect('exercice/index');
        }
        else
        {            
            $data['_view'] = 'exercice/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a exercice
     */
    function edit($ID)
    {   
        // check if the exercice exists before trying to edit it
        $data['exercice'] = $this->Exercice_model->get_exercice($ID);
        
        if(isset($data['exercice']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'STATUT' => $this->input->post('STATUT'),
					'IDIMAGE' => $this->input->post('IDIMAGE'),
					'NOM' => $this->input->post('NOM'),
					'DESCRIPTION' => $this->input->post('DESCRIPTION'),
                );

                $this->Exercice_model->update_exercice($ID,$params);            
                redirect('exercice/index');
            }
            else
            {
                $data['_view'] = 'exercice/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The exercice you are trying to edit does not exist.');
    } 

    /*
     * Deleting exercice
     */
    function remove($ID)
    {
        $exercice = $this->Exercice_model->get_exercice($ID);

        // check if the exercice exists before trying to delete it
        if(isset($exercice['ID']))
        {
            $this->Exercice_model->delete_exercice($ID);
            redirect('exercice/index');
        }
        else
            show_error('The exercice you are trying to delete does not exist.');
    }
    
}
