<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Image extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Image_model');
    } 

    /*
     * Listing of image
     */
    function index()
    {
        $data['image'] = $this->Image_model->get_all_image();
        
        $data['_view'] = 'image/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new image
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'STATUT' => $this->input->post('STATUT'),
				'DOSSIER' => $this->input->post('DOSSIER'),
				'NOM' => $this->input->post('NOM'),
				'ALT' => $this->input->post('ALT'),
            );
            
            $image_id = $this->Image_model->add_image($params);
            redirect('image/index');
        }
        else
        {            
            $data['_view'] = 'image/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a image
     */
    function edit($ID)
    {   
        // check if the image exists before trying to edit it
        $data['image'] = $this->Image_model->get_image($ID);
        
        if(isset($data['image']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'STATUT' => $this->input->post('STATUT'),
					'DOSSIER' => $this->input->post('DOSSIER'),
					'NOM' => $this->input->post('NOM'),
					'ALT' => $this->input->post('ALT'),
                );

                $this->Image_model->update_image($ID,$params);            
                redirect('image/index');
            }
            else
            {
                $data['_view'] = 'image/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The image you are trying to edit does not exist.');
    } 

    /*
     * Deleting image
     */
    function remove($ID)
    {
        $image = $this->Image_model->get_image($ID);

        // check if the image exists before trying to delete it
        if(isset($image['ID']))
        {
            $this->Image_model->delete_image($ID);
            redirect('image/index');
        }
        else
            show_error('The image you are trying to delete does not exist.');
    }
    
}
