<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Menu_model');
    } 

    /*
     * Listing of menu
     */
    function index()
    {
        $data['menu'] = $this->Menu_model->get_all_menu();
        
        $data['_view'] = 'menu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new menu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'STATUT' => $this->input->post('STATUT'),
				'NOM' => $this->input->post('NOM'),
				'LIENS' => $this->input->post('LIENS'),
				'CLASS' => $this->input->post('CLASS'),
            );
            
            $menu_id = $this->Menu_model->add_menu($params);
            redirect('menu/index');
        }
        else
        {            
            $data['_view'] = 'menu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a menu
     */
    function edit($ID)
    {   
        // check if the menu exists before trying to edit it
        $data['menu'] = $this->Menu_model->get_menu($ID);
        
        if(isset($data['menu']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'STATUT' => $this->input->post('STATUT'),
					'NOM' => $this->input->post('NOM'),
					'LIENS' => $this->input->post('LIENS'),
					'CLASS' => $this->input->post('CLASS'),
                );

                $this->Menu_model->update_menu($ID,$params);            
                redirect('menu/index');
            }
            else
            {
                $data['_view'] = 'menu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The menu you are trying to edit does not exist.');
    } 

    /*
     * Deleting menu
     */
    function remove($ID)
    {
        $menu = $this->Menu_model->get_menu($ID);

        // check if the menu exists before trying to delete it
        if(isset($menu['ID']))
        {
            $this->Menu_model->delete_menu($ID);
            redirect('menu/index');
        }
        else
            show_error('The menu you are trying to delete does not exist.');
    }
    
}
