<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Message extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Message_model');
    } 

    /*
     * Listing of message
     */
    function index()
    {
        $data['message'] = $this->Message_model->get_all_message();
        
        $data['_view'] = 'message/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new message
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'LUE' => $this->input->post('LUE'),
				'STATUT' => $this->input->post('STATUT'),
				'NOM' => $this->input->post('NOM'),
				'PRENOM' => $this->input->post('PRENOM'),
				'EMAIL' => $this->input->post('EMAIL'),
				'SUJET' => $this->input->post('SUJET'),
				'CONTENUE' => $this->input->post('CONTENUE'),
            );
            
            $message_id = $this->Message_model->add_message($params);
            redirect('message/index');
        }
        else
        {            
            $data['_view'] = 'message/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a message
     */
    function edit($ID)
    {   
        // check if the message exists before trying to edit it
        $data['message'] = $this->Message_model->get_message($ID);
        
        if(isset($data['message']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'LUE' => $this->input->post('LUE'),
					'STATUT' => $this->input->post('STATUT'),
					'NOM' => $this->input->post('NOM'),
					'PRENOM' => $this->input->post('PRENOM'),
					'EMAIL' => $this->input->post('EMAIL'),
					'SUJET' => $this->input->post('SUJET'),
					'CONTENUE' => $this->input->post('CONTENUE'),
                );

                $this->Message_model->update_message($ID,$params);            
                redirect('message/index');
            }
            else
            {
                $data['_view'] = 'message/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The message you are trying to edit does not exist.');
    } 

    /*
     * Deleting message
     */
    function remove($ID)
    {
        $message = $this->Message_model->get_message($ID);

        // check if the message exists before trying to delete it
        if(isset($message['ID']))
        {
            $this->Message_model->delete_message($ID);
            redirect('message/index');
        }
        else
            show_error('The message you are trying to delete does not exist.');
    }
    
}
