<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programme extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Programme_model');
    } 

    /*
     * Listing of programme
     */
    function index()
    {
        $data['programme'] = $this->Programme_model->get_all_programme();
        
        $data['_view'] = 'programme/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new programme
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'STATUT' => $this->input->post('STATUT'),
				'IDCATEGORIE' => $this->input->post('IDCATEGORIE'),
				'IDEXERCICE' => $this->input->post('IDEXERCICE'),
				'MOMENT' => $this->input->post('MOMENT'),
            );
            
            $programme_id = $this->Programme_model->add_programme($params);
            redirect('programme/index');
        }
        else
        {            
            $data['_view'] = 'programme/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a programme
     */
    function edit($ID)
    {   
        // check if the programme exists before trying to edit it
        $data['programme'] = $this->Programme_model->get_programme($ID);
        
        if(isset($data['programme']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'STATUT' => $this->input->post('STATUT'),
					'IDCATEGORIE' => $this->input->post('IDCATEGORIE'),
					'IDEXERCICE' => $this->input->post('IDEXERCICE'),
					'MOMENT' => $this->input->post('MOMENT'),
                );

                $this->Programme_model->update_programme($ID,$params);            
                redirect('programme/index');
            }
            else
            {
                $data['_view'] = 'programme/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The programme you are trying to edit does not exist.');
    } 

    /*
     * Deleting programme
     */
    function remove($ID)
    {
        $programme = $this->Programme_model->get_programme($ID);

        // check if the programme exists before trying to delete it
        if(isset($programme['ID']))
        {
            $this->Programme_model->delete_programme($ID);
            redirect('programme/index');
        }
        else
            show_error('The programme you are trying to delete does not exist.');
    }
    
}
