<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class A_propo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get a_propo by ID
     */
    function get_a_propo($ID)
    {
        return $this->db->get_where('A_PROPOS',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all a_propos
     */
    function get_all_a_propos()
    {
//        $this->db->order_by('ID', 'desc');
        return $this->db->get('A_PROPOS')->result_array();
    }
        
    /*
     * function to add new a_propo
     */
    function add_a_propo($params)
    {
        $this->db->insert('A_PROPOS',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update a_propo
     */
    function update_a_propo($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('A_PROPOS',$params);
    }
    
    /*
     * function to delete a_propo
     */
    function delete_a_propo($ID)
    {
        return $this->db->delete('A_PROPOS',array('ID'=>$ID));
    }
}
