<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categorie_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categorie by ID
     */
    function get_categorie($ID)
    {
        return $this->db->get_where('CATEGORIE',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all categorie
     */
    function get_all_categorie()
    {
//        $this->db->order_by('ID', 'desc');
        return $this->db->get('CATEGORIE')->result_array();
    }
        
    /*
     * function to add new categorie
     */
    function add_categorie($params)
    {
        $this->db->insert('CATEGORIE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categorie
     */
    function update_categorie($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('CATEGORIE',$params);
    }
    
    /*
     * function to delete categorie
     */
    function delete_categorie($ID)
    {
        return $this->db->delete('CATEGORIE',array('ID'=>$ID));
    }
}
