<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Exercice_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get exercice by ID
     */
    function get_exercice($ID)
    {
        return $this->db->get_where('EXERCICE',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all exercice
     */
    function get_all_exercice()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('EXERCICE')->result_array();
    }
        
    /*
     * function to add new exercice
     */
    function add_exercice($params)
    {
        $this->db->insert('EXERCICE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update exercice
     */
    function update_exercice($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('EXERCICE',$params);
    }
    
    /*
     * function to delete exercice
     */
    function delete_exercice($ID)
    {
        return $this->db->delete('EXERCICE',array('ID'=>$ID));
    }
}
