<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gallery_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gallery by ID
     */
    function get_gallery($ID)
    {
        return $this->db->get_where('GALLERY',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all gallery
     */
    function get_all_gallery()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('GALLERY')->result_array();
    }

    function get_all_DetailGallery()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('DETAILGALLERY')->result_array();
    }
        
    /*
     * function to add new gallery
     */
    function add_gallery($params)
    {
        $this->db->insert('GALLERY',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gallery
     */
    function update_gallery($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('GALLERY',$params);
    }
    
    /*
     * function to delete gallery
     */
    function delete_gallery($ID)
    {
        return $this->db->delete('GALLERY',array('ID'=>$ID));
    }
}
