<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Image_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get img by ID
     */
    function get_image($ID)
    {
        return $this->db->get_where('IMAGE',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all img
     */
    function get_all_image()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('IMAGE')->result_array();
    }
        
    /*
     * function to add new img
     */
    function add_image($params)
    {
        $this->db->insert('IMAGE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update img
     */
    function update_image($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('IMAGE',$params);
    }
    
    /*
     * function to delete img
     */
    function delete_image($ID)
    {
        return $this->db->delete('IMAGE',array('ID'=>$ID));
    }
}
