<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ouverture_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ouverture by ID
     */
    function get_ouverture($ID)
    {
        return $this->db->get_where('OUVERTURE',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all ouverture
     */
    function get_all_ouverture()
    {
//        $this->db->order_by('ID', 'desc');
        return $this->db->get('OUVERTURE')->result_array();
    }
        
    /*
     * function to add new ouverture
     */
    function add_ouverture($params)
    {
        $this->db->insert('OUVERTURE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ouverture
     */
    function update_ouverture($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('OUVERTURE',$params);
    }
    
    /*
     * function to delete ouverture
     */
    function delete_ouverture($ID)
    {
        return $this->db->delete('OUVERTURE',array('ID'=>$ID));
    }
}
