<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programme_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get programme by ID
     */
    function get_programme($ID)
    {
        return $this->db->get_where('PROGRAMME',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all programme
     */
    function get_all_programme()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('PROGRAMME')->result_array();
    }
        
    /*
     * function to add new programme
     */
    function add_programme($params)
    {
        $this->db->insert('PROGRAMME',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update programme
     */
    function update_programme($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('PROGRAMME',$params);
    }
    
    /*
     * function to delete programme
     */
    function delete_programme($ID)
    {
        return $this->db->delete('PROGRAMME',array('ID'=>$ID));
    }
}
