<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Titrepage_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get titrepage by ID
     */
    function get_titrepage($ID)
    {
        return $this->db->get_where('TITREPAGE',array('ID'=>$ID))->row_array();
    }

    function get_titrepageByPage($PAGE)
    {
        return $this->db->get_where('TITREPAGE',array('PAGE'=>$PAGE))->row_array();
    }
        
    /*
     * Get all titrepage
     */
    function get_all_titrepage()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('TITREPAGE')->result_array();
    }
        
    /*
     * function to add new titrepage
     */
    function add_titrepage($params)
    {
        $this->db->insert('TITREPAGE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update titrepage
     */
    function update_titrepage($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('TITREPAGE',$params);
    }
    
    /*
     * function to delete titrepage
     */
    function delete_titrepage($ID)
    {
        return $this->db->delete('TITREPAGE',array('ID'=>$ID));
    }
}
