<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by ID
     */
    function get_user($ID)
    {
        return $this->db->get_where('USER',array('ID'=>$ID))->row_array();
    }

    function getUser($user,$mdp){
        $users = $this->db-> get_where('USER',array('USERNAME'=>$user,'PASSWORD'=>$mdp))->row_array();
        return $users;
    }
        
    /*
     * Get all user
     */
    function get_all_user()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('USER')->result_array();
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('USER',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('USER',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($ID)
    {
        return $this->db->delete('USER',array('ID'=>$ID));
    }
}
